plugins:
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3.5
  NewCops: enable
  Exclude:
    - ".yarn/*"
    - "bin/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/migrate/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "storage/**/*"
    - "vendor/**/*"
    - "coverage/**/*"
    - "**/*.min.js"
    - "**/*.map"
    - "public/**/*"
    - "spec/fixtures/**/*"

RSpecRails/InferredSpecType:
  Enabled: false

Layout/LineLength:
  Max: 120 # Default is 80 characters

Metrics/BlockLength:
  Max: 30 # Default is 25

Style/Documentation:
  Exclude:
    - "**/application_*.rb"
    - "config/application.rb"

RSpec/NestedGroups:
  Max: 4 # Default is 3
