// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import FlashController from "./flash_controller";
application.register("flash", FlashController);

import SearchController from "./search_controller";
application.register("search", SearchController);

import ItemLocationController from "./item_location_controller";
application.register("item-location", ItemLocationController);

import TurboNavigatorController from "./turbo_navigator_controller";
application.register("turbo-navigator", TurboNavigatorController);
